title: Taewook Kim
logo: /assets/img/taewook_mint.jpg
email: Northwestern University
description: HCI
show_downloads: false
google_analytics: UA-123511119-1
# theme: jekyll-theme-minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

remote_theme: BDHU/minimalist